### ISSUE TITLE
switch/case fix needed

### ISSUE THREAD

**Issue by hirdrac** [zaimoni/Cataclysm#170]
https://github.com/zaimoni/Cataclysm/blob/bedc573cf6f4f9e159f503b9d249bb07d5670789/npcmove.cpp#L413
add a break or [[fallthrough]] after this statement depending on what was intended

**Comment by zaimoni** [comment]
Formal-fixed by bd0d4996c7d1adc8a90dff6e7c93171bf75cfc07 .
