### ISSUE TITLE
Excessive warnings when compiling with warnings enabled

### ISSUE THREAD

**Issue by hirdrac** [zaimoni/Cataclysm#54]
There's an abnormally large number of warnings when compiling with warnings enabled - some of these warnings indicate problems that need addressing.  Running the game now on Linux often results in crashes so I'm looking at cleaning up some of the more obvious issues first before I dive into the code too deeply.

**Comment by zaimoni** [comment]
Ok.  A numerically large category of warnings on my end are from constructs of the form intvar *= float (this shows as a truncation from floating point to integer).

In cases where the warning indicates an actual behavior change, my preferred fix strategy for this is the rational_scale and rational_scaled template functions (defined in stl_limits.h).  Example usage for rational_scale is at player.cpp lines 3588ff .  The currently sole use of rational_scaled is at player.cpp: 1803 (this was more of a lines-of-code reduction while I was auditing something else).

**Comment by hirdrac** [comment]
This probably can be closed now - while more improvements could be made, all of the most troubling warnings have been dealt with.
