### ISSUE TITLE
direction_vector skewed, badly

### ISSUE THREAD

**Issue by zaimoni** [zaimoni/Cataclysm#80]
This *plausibly* was causing problems for multiple versions, but became Przybylski's Star when the player move/drive functions were converted to raw C enumeration mapping.

Elevated to Przybylski's Star by 41eba328af0deaaa31f912127f9a7b23a5ec50b0 ; fixed by 61f0f4bd72b46b73e962bb246875149dbf0d740f .  Checkpoints for August 25-27 2020 were Przybylski's Star stability, and were withdrawn on the upload of the August 28 2020 checkpoint.

**Comment by Zireael07** [comment]
Przybylski's Star :D
