### ISSUE TITLE
Crash when trying to press up/down in Encumberance tab of Player stats screen

### ISSUE THREAD

**Issue by mount2010** [zaimoni/Cataclysm#92]
I've tried compiling both the game from the Master branch and from source code from the 0.2.3 (0.2.4?) release. 
In both cases, trying to navigate up and down in the Encumberance tab of the players stats screen causes a crash, with the following messages:
`what():  unexpected escape % use`
`terminate called after throwing an instance of 'std::logic_error'`

gcc (Ubuntu 10.1.0-2ubuntu1\~18.04) 10.1.0
g++ (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0

**Comment by hirdrac** [comment]
Well that's not good!  For now you can comment out line 171 from output.cpp:
  **if (!strchr("%sidc", src[i + 1])) throw std::logic_error("unexpected escape % use");**

(it's trying a bit too hard to reject invalid C-style format sequences and it chokes on fancy floating point syntax)
I'm sure Zaimoni will fix it once he wakes up (or comes home from work?  don't know what time zone he's in)

**Comment by zaimoni** [comment]
If those escape sequences are not rejected in software, they hard-crash on MSVC++ (crash to desktop, no logging possible).

This at least gives an audit trail.

**Comment by zaimoni** [comment]
Ok...looks like the player encumbrance screen is the *one* place that uses formatted floating point.  Formal-fixed by c45aa60592686ab1eff62036c19daf0c41afac22 .
